### PR TITLE
Add source installs from pggb Dockerfile

### PR DESCRIPTION
**Pull request by heuermh**
Adds source installs of `edyeet`, `wfmash`, `seqwish`, `smoothxg`, `odgi` from https://github.com/pangenome/pggb/blob/master/Dockerfile at commit https://github.com/pangenome/pggb/commit/96c567d9c3327fb6b4d2792a0f75053f8039dfff.

### CODE REVIEW

**Comment by heuermh** [comment]
Still failing to build
```
[ 72%] Building CXX object CMakeFiles/odgi_objs.dir/src/unittest/edge.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[5]: *** [CMakeFiles/odgi_objs.dir/build.make:154: CMakeFiles/odgi_objs.dir/src/unittest/driver.cpp.o]
Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/Makefile2:527: CMakeFiles/odgi_objs.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/odgi.dir/build.make:111: odgi-prefix/src/odgi-stamp/odgi-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:348: CMakeFiles/odgi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Odd that upstream seems to work on Github Actions https://github.com/pangenome/pggb/actions/runs/356302699

**Comment by subwaystation** [comment]
> Still failing to build
> 
> ```
> [ 72%] Building CXX object CMakeFiles/odgi_objs.dir/src/unittest/edge.cpp.o
> c++: fatal error: Killed signal terminated program cc1plus
> compilation terminated.
> make[5]: *** [CMakeFiles/odgi_objs.dir/build.make:154: CMakeFiles/odgi_objs.dir/src/unittest/driver.cpp.o]
> Error 1
> make[5]: *** Waiting for unfinished jobs....
> make[4]: *** [CMakeFiles/Makefile2:527: CMakeFiles/odgi_objs.dir/all] Error 2
> make[3]: *** [Makefile:130: all] Error 2
> make[2]: *** [CMakeFiles/odgi.dir/build.make:111: odgi-prefix/src/odgi-stamp/odgi-build] Error 2
> make[1]: *** [CMakeFiles/Makefile2:348: CMakeFiles/odgi.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```
> 
> Odd that upstream seems to work on Github Actions https://github.com/pangenome/pggb/actions/runs/356302699

Where you able to resolve this on your MacOS machine? Did it work on a Linux machine?

**Comment by heuermh** [comment]
> Where you able to resolve this on your MacOS machine? Did it work on a Linux machine?

I was able to get the `pggb` Dockerfile to build on OSX and linux after commit https://github.com/pangenome/pggb/commit/96c567d9c3327fb6b4d2792a0f75053f8039dfff.

Now I am still wondering if the better approach is to start `FROM nfcore/base` (which includes `conda`) and add the source installs from the `pggb` Dockerfile, or start `FROM ghcr.io/pangenome/pggb` and add `conda` &c.

**Comment by heuermh** [comment]
This works for me, so I will merge commits and force push to clean up history

**Comment by heuermh** [comment]
Closing in favor of #4

**Pull request closed without merging**
