### PR TITLE
use FROM ghcr.io/pangenome/pggb:latest

### PR DESCRIPTION
**Pull request by heuermh**
Work in progress

### CODE REVIEW

**Comment by heuermh** [comment]
Thanks for the changes!  Unfortunately the path is still not set correctly
```
$ docker build --no-cache . -t nfcore/pangenome:dev
...
Successfully tagged nfcore/pangenome:dev

(base) nf-core-pangenome docker-alt
$ nextflow run main.nf -profile test,docker
...
Command error:
  /usr/bin/env: 'python': Permission denied

$ docker run -it nfcore/pangenome:dev /bin/bash
root@c31c6b6a916c:/# which python
root@c31c6b6a916c:/# env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@c31c6b6a916c:/# exit
```

I think I have a fix though, moving the `/etc/profile` line later, will push another commit.

**Comment by heuermh** [comment]
With commit 1f43d29 the container path is correct and the workflow (as it is) makes it farther

```
(base) nf-core-pangenome docker-alt!
$ docker run -it nfcore/pangenome:dev /bin/sh
# which python
/root/miniconda3/bin/python
# env | grep PATH
PATH=/opt/conda/envs/nf-core-pangenome-1.0dev/bin:/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

(base) nf-core-pangenome docker-alt!
$ nextflow run main.nf -profile test,docker
...
Command error:
  .command.sh: line 4: fastqc: command not found
```

which is to be expected, as `fastqc` will not be used in this workflow.

**Comment by Zethson** [comment]
@heuermh Sorry, i was not following this PR and therefore got no notifications.
I only tested Conda and not Python, but I'm glad to see that you have it figured out.

So this PR is ready I guess?

We can add the dependencies that we need as we go.

**Comment by heuermh** [comment]
Yes, this is ready for review, if we prefer it over #2

**Comment by Zethson** [comment]
I would say so.

LGTM

**Comment by heuermh** [comment]
Thank you, @Zethson

**Pull request merged**
